#!/bin/bash

if command -v apt &> /dev/null; then
    sudo apt install make mingw-w64 build-essential libssl-dev uuid-dev pkgconf
elif command -v brew &> /dev/null; then
    #TODO
    exit 11
elif command -v dnf &> /dev/null; then
    #TODO
    exit 11
elif command -v yum &> /dev/null; then
    #TODO
    exit 11
else
    echo "No package manager was recognized. no required dependencies were installed"
    exit 11
fi
